### ISSUE TITLE
What is the difference between this library and TagTree?

### ISSUE THREAD

**Issue by Emasoft** [cleandart/tiles#35]
I'm looking for the best React like library written directly in Dart (natively, no bindings. I need speed).
Some time ago I found TagTree and I started working with it:
https://github.com/google/dart-tagtree
Now I've found Tiles (or DartTiles, to avoid confusion). But it is not clear to me what is the difference between the two, and what are the advantages of DartTiles compared to TagTree. Can you elaborate a little about this? I'm asking because I'm not an expert of the original React library, so it is difficult for me to see what library is more fit for my Dart project. Thanks.

**Comment by jakuub** [comment]
Just an update - tiles are isomorphic now. The main part is tiles_console.dart and the method `renderToString` which get ComponentDescription as parameter and returned string with HTML of the corresponding descritpion. The HTML rendered this way on server will be automaticaly "infected" by functionality in browser without redraw.
